ARG RUST_VERSION=1.90-slim

FROM rust:${RUST_VERSION} AS dev

WORKDIR /app

COPY Cargo.toml . 

COPY src/ ./src

RUN apt-get update -y && apt-get install -y libsqlite3-dev && rm -rf /var/lib/apt/lists/*


EXPOSE 4000
